version: '3.7'
services: 
    elements-api:
        container_name: elements-api
        restart: unless-stopped
        build:
            context: ./
        ports:
          - 8080:8080            
    caddy:
        image: caddy/caddy:2.5.2-alpine
        container_name: caddy-server
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
        volumes:            
        - ./Caddyfile:/etc/caddy/Caddyfile
        - ./site:/srv
        - caddy_data:/data
        - caddy_config:/config

volumes:
  caddy_data:
  caddy_config: 